package smeldr

import (
	"context"
	"errors"
	"fmt"
	"html/template"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"runtime/debug"
	"slices"
	"strings"
	"sync"
	"syscall"
	"time"
)

// Default timeout values applied by New when the caller does not set them
// in Config. These are conservative production defaults.
const (
	defaultReadTimeout  = 5 * time.Second
	defaultWriteTimeout = 10 * time.Second
	defaultIdleTimeout  = 120 * time.Second
)

// Config holds the application-wide configuration passed to [New].
//
// BaseURL and Secret are required; all other fields are optional.
//
// Timeouts default to 5 s (read), 10 s (write), and 120 s (idle) when left as
// zero. Set them explicitly to override.
type Config struct {
	// BaseURL is the canonical URL of the site, e.g. "https://example.com"
	// (no trailing slash). Required.
	BaseURL string

	// Secret is the HMAC signing key used by [BearerHMAC], [CookieSession], and
	// [SignToken]. It must be at least 16 bytes. Required.
	//
	// When Auth is nil, Secret is used to validate Bearer tokens automatically
	// via [BearerHMAC]. Set [Config.Auth] to override.
	Secret []byte

	// Auth is the [AuthFunc] used to authenticate requests. When nil, Forge
	// defaults to [BearerHMAC] using [Config.Secret]. Set this explicitly to
	// use [CookieSession], [AnyAuth], or a custom [AuthFunc].
	//
	// Example — cookie sessions instead of bearer tokens:
	//
	//	Auth: smeldr.CookieSession("session", secret)
	//
	// Example — both bearer tokens and cookie sessions:
	//
	//	Auth: smeldr.AnyAuth(
	//	    smeldr.BearerHMAC(secret),
	//	    smeldr.CookieSession("session", secret),
	//	)
	Auth AuthFunc

	// TokenStore enables database-backed named bearer token management. When
	// set, [VerifyBearerToken] checks the smeldr_tokens table to validate that
	// a token has not been revoked. The smeldr_tokens table must exist before
	// the application starts; see [TokenStore] for the required DDL.
	// Optional — leave nil to use HMAC-only token validation.
	TokenStore *TokenStore

	// Version is the application version string. It is an optional field for
	// application authors who want to track their own release version; forge
	// itself does not use this field in any built-in endpoint.
	Version string

	// DB is the database connection used by content modules.
	// It accepts *sql.DB, *sql.Tx, or any value that satisfies [DB].
	// Optional — leave nil to use in-memory repositories only.
	DB DB

	// HTTPS forces an HTTP→HTTPS redirect for all plain-HTTP requests when
	// true. The App handler checks r.TLS and the X-Forwarded-Proto header so
	// this works correctly behind a reverse proxy. Optional.
	HTTPS bool

	// ReadTimeout is the maximum time to read the full request, including the
	// body. Defaults to 5 s. Optional.
	ReadTimeout time.Duration

	// WriteTimeout is the maximum time to write the full response. Defaults to
	// 10 s. Optional.
	WriteTimeout time.Duration

	// IdleTimeout is the maximum keep-alive idle time between requests.
	// Defaults to 120 s. Optional.
	IdleTimeout time.Duration

	// PreviewTokenExpiry sets how long a preview token generated by
	// [App.GeneratePreviewToken] remains valid. Defaults to 12 hours when zero.
	// Optional.
	PreviewTokenExpiry time.Duration

	// NavMode selects how the application's navigation tree is populated.
	// Use [NavModeDB] to persist navigation items in the smeldr_nav database
	// table (requires [Config.DB]; panics at startup if DB is nil).
	// Use [NavModeCode] to supply items directly via [App.Nav].
	// The zero value disables navigation entirely. Optional.
	NavMode NavMode

	// AppSchema sets the app-level JSON-LD structured data block emitted on
	// every page as a <script type="application/ld+json"> element. When set
	// here, it is applied automatically at startup; an explicit [App.SEO] call
	// with an [AppSchema] takes precedence. This field is also populated when
	// a smeldr.config file contains the org_name or org_type keys. Optional.
	AppSchema *AppSchema

	// OGDefaults sets the app-level Open Graph and Twitter Card fallback values
	// applied to every page. When set here, it is applied automatically at
	// startup; an explicit [App.SEO] call with an [OGDefaults] takes
	// precedence. Also populated from smeldr.config og_image and twitter_site
	// keys. Optional.
	OGDefaults *OGDefaults

	// MediaPath is the filesystem directory where forge-media stores uploaded
	// files. Defaults to "./media" when zero. Optional — only read by
	// forge-media; ignored by forge core.
	MediaPath string

	// MediaMaxSize is the maximum permitted upload size in bytes. Defaults to
	// 5242880 (5 MB) when zero. Optional — only read by forge-media; ignored
	// by forge core.
	MediaMaxSize int64

	// MediaUploadTokenExpiry sets how long an upload token generated by
	// [App.GenerateUploadToken] remains valid. Defaults to 15 minutes when
	// zero. Optional — only read by forge-media; ignored by forge core.
	MediaUploadTokenExpiry time.Duration

	// Dev enables development mode. When true, [App.Static] serves files from
	// disk (devDir) instead of the embedded FS, so changes are visible without
	// rebuilding. Set from os.Getenv("DEV") == "1" or via the smeldr.config key
	// "dev = true". Optional.
	Dev bool

	// WebhookWorkers is the number of concurrent goroutines that poll and
	// deliver outbound webhook jobs. Defaults to 10 when zero. Optional —
	// only used when [App.Webhooks] is called.
	WebhookWorkers int
}

// MustConfig validates cfg and returns it unchanged.
//
// Panics with a descriptive message if:
//   - Config.BaseURL is empty or not a valid absolute URL
//   - Config.Secret is fewer than 16 bytes
//
// MustConfig also loads a smeldr.config file from the working directory (or the
// path set in the SMELDR_CONFIG environment variable) and merges its key/value
// pairs into cfg. Go-code field values always take precedence over file values.
// Supported smeldr.config keys: base_url, https, nav_mode, org_name, org_type,
// twitter_site, og_image, media_path, media_max_size, dev.
// The key "secret" is explicitly forbidden in smeldr.config and causes a panic.
//
// Typical usage:
//
//	app := smeldr.New(smeldr.MustConfig(smeldr.Config{
//	    BaseURL: os.Getenv("BASE_URL"),
//	    Secret:  []byte(os.Getenv("SECRET")),
//	}))
func MustConfig(cfg Config) Config {
	// D30: load smeldr.config (or the path in SMELDR_CONFIG) and merge file
	// values into cfg. Go-code fields always take precedence.
	if path := os.Getenv("SMELDR_CONFIG"); path != "" {
		fc, err := loadConfigFile(path)
		if err != nil {
			panic("smeldr: " + err.Error())
		}
		cfg = mergeFileConfig(cfg, fc)
	} else {
		fc, _ := loadConfigFile("smeldr.config") // missing file is not an error
		cfg = mergeFileConfig(cfg, fc)
	}
	if cfg.BaseURL == "" {
		panic(`smeldr: Config.BaseURL is required (e.g. "https://example.com")`)
	}
	u, err := url.ParseRequestURI(cfg.BaseURL)
	if err != nil || !u.IsAbs() {
		panic(fmt.Sprintf("smeldr: Config.BaseURL %q is not a valid absolute URL: %v", cfg.BaseURL, err))
	}
	if len(cfg.Secret) < 16 {
		panic("smeldr: Config.Secret must be at least 16 bytes")
	}
	return cfg
}

// Registrator is implemented by any value that can register its HTTP routes on
// a [http.ServeMux]. [*Module] satisfies this interface automatically.
//
// Pass a pre-built [*Module] to [App.Content] to register it:
//
//	posts := smeldr.NewModule[*Post](&Post{}, smeldr.Repo(repo))
//	app.Content(posts)
type Registrator interface {
	Register(mux *http.ServeMux)
}

// SEOOption is implemented by any value that modifies the app-level SEO
// configuration. Pass SEOOption values to [App.SEO]:
//
//	app.SEO(&smeldr.RobotsConfig{AIScraper: smeldr.AskFirst, Sitemaps: true})
type SEOOption interface {
	applySEO(*seoState)
}

// seoState holds the app-level SEO configuration applied via [App.SEO].
type seoState struct {
	robots     *RobotsConfig
	ogDefaults *OGDefaults
	appSchema  *AppSchema
	headAssets *HeadAssets
}

// standaloneDispatcher is the internal interface implemented by [Module] instances
// that use the [Standalone] option. [App] uses it to route GET /{slug} and
// GET /{slug}/aidoc requests at the top level rather than under the module prefix.
type standaloneDispatcher interface {
	standaloneEnabled() bool
	findAndServe(w http.ResponseWriter, r *http.Request, slug string) bool
	findAndServeAIDoc(w http.ResponseWriter, r *http.Request, slug string) bool
}

// App is the central registry for a Forge application. It couples the HTTP
// router, global middleware, and all content modules into a single value.
//
// Create an App with [New], wire in modules with [App.Content], add global
// middleware with [App.Use], then serve with [App.Run] or [App.Handler].
//
// Optional cross-cutting features are configured directly on the App:
//   - [App.SEO] — robots.txt, sitemap index, AI-crawler policy
//   - [App.Cookies] + [App.CookiesManifestAuth] — typed cookie compliance manifest
//   - [App.Redirect] + [App.RedirectStore] + [App.RedirectManifestAuth] — redirect rules
//
// App is not safe for concurrent configuration: set it up in main before
// calling Run or Handler, then treat it as read-only.
type App struct {
	cfg                    Config
	mux                    *http.ServeMux
	middleware             []func(http.Handler) http.Handler
	sitemapStore           *SitemapStore                       // non-nil when at least one module has SitemapConfig
	sitemapIndexRegistered bool                                // true once GET /sitemap.xml is registered
	seo                    seoState                            // app-level SEO configuration set via SEO()
	robotsTxtRegistered    bool                                // true once GET /robots.txt is registered
	templateModules        []templateParser                    // modules with HTML templates; parsed at Run() time
	llmsStore              *LLMsStore                          // non-nil when at least one module uses AIIndex
	llmsTxtRegistered      bool                                // true once GET /llms.txt is registered
	llmsFullTxtRegistered  bool                                // true once GET /llms-full.txt is registered
	feedStore              *FeedStore                          // non-nil when at least one module uses Feed(...)
	feedIndexRegistered    bool                                // true once GET /feed.xml is registered
	cookieDecls            []Cookie                            // registered via Cookies(); drives /.well-known/cookies.json
	cookieManifestOpts     []Option                            // options for the manifest handler (e.g. ManifestAuth)
	cookieManifestReg      bool                                // true once GET /.well-known/cookies.json is registered
	redirectStore          *RedirectStore                      // runtime redirect table; always non-nil after New()
	redirectDB             DB                                  // non-nil when App.Redirects(db) was called; enables MCP tools
	statsCollectors        []statsCollector                    // modules that implement statsCollector; populated by Content()
	statsExtProviders      []StatsExtProvider                  // external providers registered via RegisterStatsProvider
	blockParents           []ContentParentProvider             // modules that opted into block hosting via BlockHost(); populated by Content()
	redirectFallbackReg    bool                                // true once "/" fallback handler is registered
	redirectManifestReg    bool                                // true once GET /.well-known/redirects.json is registered
	redirectManifestOpts   []Option                            // options for the redirect manifest handler (e.g. ManifestAuth)
	schedulerModules       []schedulableModule                 // modules that implement scheduled publishing
	rebuilderModules       []rebuilder                         // modules with derived content (sitemap, feed, AI)
	stoppableModules       []stoppable                         // modules with background goroutines to stop at shutdown
	mcpModules             []MCPModule                         // modules registered with smeldr.MCP(...)
	standaloneModules      []standaloneDispatcher              // Standalone() modules; for top-level /{slug} dispatch
	standaloneReg          bool                                // true once GET /{slug} and GET /{slug}/aidoc are registered
	typeRegistry           *ContentTypeRegistry                // content-type registry; always non-nil after New()
	dynamicContentEnabled  bool                                // true after ServeDynamicContent() is called
	dynamicContentReg      bool                                // true once /_content/ routes and 2-segment dispatcher are registered
	dynamicTypesLoaded     bool                                // guards loadDynamicTypes idempotency
	rebuildDone            bool                                // true once startup rebuildAll goroutine is launched
	partialsDir            string                              // set by App.Partials(); shared partial templates loaded at Run() time
	tokenStore             *TokenStore                         // non-nil when Config.TokenStore is set; enables DB-backed token management
	navTree                *NavTree                            // non-nil when NavMode is set or App.Nav() is called
	navCodeItems           []NavItem                           // items supplied via App.Nav() for NavModeCode
	navTreeModules         []interface{ setNavTree(*NavTree) } // modules that receive the navTree after startup

	auditStore      AuditStore // non-nil when App.Audit() was called
	auditHandlerReg bool       // true once GET /_audit is registered

	logRing        *logRing // non-nil when App.CaptureLogs() was called; backs GET /_logs
	logsHandlerReg bool     // true once GET /_logs is registered

	webhookStore    *WebhookStore               // non-nil when App.Webhooks() was called
	webhookPool     *workerPool                 // non-nil when App.Webhooks() was called
	signalListeners []func(Signal, string, any) // registered via AddSignalListener
	busMu           sync.RWMutex
	busHandlers     map[Signal][]func(context.Context, SignalEvent) error // registered via OnSignal
	hookableModules []interface {
		setAfterHook(func(Context, Signal, afterHookMeta, any))
	} // modules whose afterHook is wired at Run time
}

// New creates a new [App] from cfg.
//
// New calls [MustConfig] on cfg automatically, so it panics at startup if
// BaseURL is empty or not a valid absolute URL, or if Secret is shorter than
// 16 bytes. Configuration errors are always caught at process start, never at
// first request.
//
// Default timeouts are applied if the corresponding Config fields are zero:
// ReadTimeout 5 s, WriteTimeout 10 s, IdleTimeout 120 s.
func New(cfg Config) *App {
	cfg = MustConfig(cfg)
	if cfg.ReadTimeout == 0 {
		cfg.ReadTimeout = defaultReadTimeout
	}
	if cfg.WriteTimeout == 0 {
		cfg.WriteTimeout = defaultWriteTimeout
	}
	if cfg.IdleTimeout == 0 {
		cfg.IdleTimeout = defaultIdleTimeout
	}
	auth := cfg.Auth
	if auth == nil {
		auth = BearerHMAC(string(cfg.Secret))
	}
	app := &App{
		cfg:           cfg,
		mux:           http.NewServeMux(),
		middleware:    []func(http.Handler) http.Handler{Authenticate(auth)},
		redirectStore: NewRedirectStore(),
		tokenStore:    cfg.TokenStore,
		typeRegistry:  newContentTypeRegistry(),
	}
	if cfg.DB != nil {
		if err := migrateLegacyTableNames(context.Background(), cfg.DB); err != nil {
			slog.Warn("smeldr: legacy table migration failed — rename forge_* tables manually", "error", err)
		}
	}
	return app
}

// Use appends one or more global middleware to the App's middleware stack.
//
// Middleware is applied in the order it is added: the first call to Use wraps
// the outermost layer. Use may be called multiple times; all calls are
// additive.
//
//	app.Use(smeldr.RequestLogger(), smeldr.Recoverer(), smeldr.SecurityHeaders())
func (a *App) Use(mws ...func(http.Handler) http.Handler) {
	a.middleware = append(a.middleware, mws...)
}

// Handle registers a raw [http.Handler] at the given pattern on the App's
// internal mux. The pattern follows the same rules as [http.ServeMux].
//
// Use Handle for endpoints that are not managed by a [Module]:
//
//	app.Handle("GET /healthz", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
//	    w.WriteHeader(http.StatusOK)
//	}))
func (a *App) Handle(pattern string, handler http.Handler) {
	a.mux.Handle(pattern, handler)
}

// Partials sets the directory from which shared HTML partial templates are
// loaded. Every *.html file in dir is registered into each module's template
// set (list.html and show.html) at [App.Run] time, making them available via:
//
//	{{template "nav" .}}
//
// Each partial file must use {{define "name"}}...{{end}} syntax. Any name
// except "forge:head" may be used. Files are registered in alphabetical order.
//
// Partials returns the App so multiple calls can be chained:
//
//	app.Partials("templates/partials")
//
// Use [App.MustParseTemplate] to parse custom handler templates (e.g. a home
// page) with the same partials and forge:head registered.
func (a *App) Partials(dir string) *App {
	a.partialsDir = dir
	return a
}

// MustParseTemplate parses the HTML template at path and registers
// [TemplateFuncMap], the forge:head partial, and any partials configured via
// [App.Partials]. Panics on any error.
//
// Use this for custom route handlers that need access to the same shared
// partials as module templates:
//
//	app.Partials("templates/partials")
//	homeTpl := app.MustParseTemplate("templates/home.html")
//	app.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
//	    homeTpl.Execute(w, data)
//	}))
func (a *App) MustParseTemplate(path string) *template.Template {
	partials, err := loadPartials(a.partialsDir)
	if err != nil {
		panic(fmt.Sprintf("smeldr: MustParseTemplate: %v", err))
	}
	tpl, err := parseOneTemplate(path, true, partials)
	if err != nil {
		panic(fmt.Sprintf("smeldr: MustParseTemplate %q: %v", path, err))
	}
	return tpl
}

// Content registers a content module with the App.
//
// If v implements [Registrator] (which [*Module] does), its Register method is
// called directly and opts are ignored. This is the idiomatic path:
//
//	posts := smeldr.NewModule[*Post](&Post{}, smeldr.Repo(repo), smeldr.At("/posts"))
//	app.Content(posts)
//
// If v does not implement [Registrator], Content calls [NewModule][any](v,
// opts...) and registers the result. In this case smeldr.Repo must be supplied
// as a repoOption[any] — type safety is lost. Prefer the [Registrator] path
// for all production code.
func (a *App) Content(v any, opts ...Option) {
	// Extract any redirect options regardless of Registrator path.
	for _, o := range opts {
		if ro, ok := o.(redirectsOption); ok {
			a.redirectStore.Add(RedirectEntry{
				From:     string(ro.from),
				To:       ro.to,
				Code:     Permanent,
				IsPrefix: true,
			})
		}
	}
	if r, ok := v.(Registrator); ok {
		r.Register(a.mux)
		if sm, ok := r.(interface{ setSitemap(*SitemapStore, string) }); ok {
			if a.sitemapStore == nil {
				a.sitemapStore = NewSitemapStore()
			}
			sm.setSitemap(a.sitemapStore, a.cfg.BaseURL)
		}
		if tp, ok := r.(templateParser); ok {
			a.templateModules = append(a.templateModules, tp)
		}
		if sn, ok := r.(interface{ setSiteName(string) }); ok {
			u, _ := url.Parse(a.cfg.BaseURL)
			sn.setSiteName(u.Hostname())
		}
		if ai, ok := r.(interface{ setAIRegistry(*LLMsStore, string) }); ok {
			if a.llmsStore == nil {
				u, _ := url.Parse(a.cfg.BaseURL)
				a.llmsStore = NewLLMsStore(u.Hostname())
			}
			ai.setAIRegistry(a.llmsStore, a.cfg.BaseURL)
		}
		if fd, ok := r.(interface{ setFeedStore(*FeedStore, string) }); ok {
			if a.feedStore == nil {
				u, _ := url.Parse(a.cfg.BaseURL)
				a.feedStore = NewFeedStore(u.Hostname(), a.cfg.BaseURL)
			}
			fd.setFeedStore(a.feedStore, a.cfg.BaseURL)
		}
		if sm, ok := r.(schedulableModule); ok {
			a.schedulerModules = append(a.schedulerModules, sm)
		}
		if rb, ok := r.(rebuilder); ok {
			a.rebuilderModules = append(a.rebuilderModules, rb)
		}
		if sp, ok := r.(stoppable); ok {
			a.stoppableModules = append(a.stoppableModules, sp)
		}
		if sc, ok := r.(statsCollector); ok {
			a.statsCollectors = append(a.statsCollectors, sc)
		}
		if mm, ok := r.(MCPModule); ok && len(mm.MCPMeta().Operations) > 0 {
			a.mcpModules = append(a.mcpModules, mm)
		}
		if mm, ok := r.(MCPModule); ok {
			if meta := mm.MCPMeta(); meta.TypeName != "" {
				// Compiled modules may share a Go struct type (same TypeName) while
				// appearing at different URL prefixes (e.g. two Module[*Post] at
				// /posts and /articles). The first call registers the descriptor;
				// subsequent calls for the same TypeName register as aliases.
				// The panicking Register() path is reserved for runtime types
				// (define_content_type, T104 increment 2+).
				if a.typeRegistry.Lookup(meta.TypeName) == nil {
					a.typeRegistry.Register(&TypeDescriptor{
						Name:   meta.TypeName,
						Prefix: meta.Prefix,
						Kind:   "content",
					})
				} else if meta.Prefix != "" {
					a.typeRegistry.RegisterPrefix(meta.Prefix, meta.TypeName)
				}
				if cl, ok := r.(ContentLister); ok {
					if desc := a.typeRegistry.Lookup(meta.TypeName); desc != nil {
						desc.Fetch = cl.listPublished
					}
				}
			}
		}
		if sd, ok := r.(standaloneDispatcher); ok && sd.standaloneEnabled() {
			a.standaloneModules = append(a.standaloneModules, sd)
		}
		if bh, ok := r.(blockHostProvider); ok && bh.blockHostEnabled() {
			a.blockParents = append(a.blockParents, bh)
		}
		if nt, ok := r.(interface{ setNavTree(*NavTree) }); ok {
			a.navTreeModules = append(a.navTreeModules, nt)
		}
		if ps, ok := r.(interface{ setSecret([]byte) }); ok {
			ps.setSecret(a.cfg.Secret)
		}
		if hk, ok := r.(interface {
			setAfterHook(func(Context, Signal, afterHookMeta, any))
		}); ok {
			a.hookableModules = append(a.hookableModules, hk)
		}
		return
	}
	// NewModule is called with an any-typed value — type assertion to any loses
	// generic type safety. See App.Content godoc for the preferred Registrator path.
	m := NewModule(v, opts...)
	m.Register(a.mux)
}

// MCPModules returns all content modules registered with [MCP].
// forge-mcp calls this once in its New constructor to build its resource and
// tool registry. The returned slice is the App's live internal slice and must
// not be modified by the caller.
func (a *App) MCPModules() []MCPModule { return a.mcpModules }

// TypeRegistry returns the app's content-type registry. Compiled modules are
// registered at [App.Content] time; runtime-defined types are registered when
// define_content_type is called (T104 increment 2+). T96 (ContentList resolver)
// and T06 (relation endpoints) share this registry.
func (a *App) TypeRegistry() *ContentTypeRegistry { return a.typeRegistry }

// Config returns a copy of the application configuration. It is intended for
// use by companion packages (such as forge-media) that need access to
// configuration fields — [Config.BaseURL], [Config.MediaPath],
// [Config.MediaMaxSize] — without the host application repeating those values
// at the call site. The returned value is a copy and cannot be used to mutate
// the running configuration.
func (a *App) Config() Config { return a.cfg }

// Secret returns the HMAC signing secret from the application configuration.
// It is intended for use by forge-mcp and other companion packages that must
// verify tokens minted with [SignToken] but cannot access [Config] directly.
func (a *App) Secret() []byte { return a.cfg.Secret }

// BaseURL returns the canonical base URL of the application (Config.BaseURL),
// without a trailing slash. It is intended for use by forge-mcp and other
// companion packages that build absolute URLs.
func (a *App) BaseURL() string { return strings.TrimRight(a.cfg.BaseURL, "/") }

// GeneratePreviewToken returns a signed preview token for the given module
// prefix and content slug. The token is valid for [Config.PreviewTokenExpiry]
// (default 12 h). Pass it to the module's show endpoint via the ?preview=
// query parameter to bypass the Published-only visibility guard for draft content.
//
// Example — build a full preview URL:
//
//	token := app.GeneratePreviewToken("posts", "my-draft")
//	url := app.BaseURL() + "/posts/my-draft?preview=" + token
//
// The token binds both prefix and slug so that a token for /posts/foo cannot
// be replayed on /docs/foo.
func (a *App) GeneratePreviewToken(prefix, slug string) string {
	ttl := a.cfg.PreviewTokenExpiry
	if ttl == 0 {
		ttl = 12 * time.Hour
	}
	return encodePreviewToken(prefix, slug, a.cfg.Secret, ttl)
}

// GenerateUploadToken returns a short-lived signed token that authorises a
// single POST /media upload request without a full bearer token. The token is
// valid for [Config.MediaUploadTokenExpiry] (default 15 m). Pass it in the
// Authorization header as "UploadToken <token>".
//
// Example — generate a token and hand it to an HTTP client:
//
//	token := app.GenerateUploadToken()
//	uploadURL := app.BaseURL() + "/media"
//
// The token carries no slug or prefix binding; it authorises any upload within
// the TTL. forge-media restricts UploadToken uploads to image MIME types only.
func (a *App) GenerateUploadToken() string {
	ttl := a.cfg.MediaUploadTokenExpiry
	if ttl == 0 {
		ttl = 15 * time.Minute
	}
	return encodeUploadToken(a.cfg.Secret, ttl)
}

// ValidateUploadToken verifies a token produced by [GenerateUploadToken].
// Returns nil when the token is valid and unexpired, or [ErrUnauth] otherwise.
// Intended for use by forge-media's upload handler.
func (a *App) ValidateUploadToken(token string) error {
	return decodeUploadToken(token, a.cfg.Secret)
}

// TokenStore returns the configured [TokenStore] for database-backed named
// token management, or nil when token management is not configured. forge-mcp
// calls this in its New constructor to wire token tools and revocation checks.
func (a *App) TokenStore() *TokenStore { return a.tokenStore }

// Webhooks wires an outbound webhook delivery engine into the application.
// Call this after [App.Content] has registered all modules and before
// [App.Run]:
//
//	store := smeldr.NewWebhookStore(db, secret)
//	app.Webhooks(store)
//
// At [App.Run] time, Forge injects the signal bus into every registered
// content module. After each lifecycle signal (create, update, publish,
// schedule, archive, delete), the bus dispatches to all registered handlers,
// including the webhook delivery handler registered here. The handler looks up
// active subscriptions from the store, builds the event payload, and enqueues
// an [OutboundJob] for the worker pool to deliver.
//
// The worker pool starts when [App.Run] is called and stops on graceful
// shutdown. The number of workers defaults to 10; set [Config.WebhookWorkers]
// to override.
//
// Webhooks requires [Config.DB] to be set — the same DB is shared with the
// store and the outbound job tables.
func (a *App) Webhooks(store *WebhookStore) *App {
	a.webhookStore = store
	workers := a.cfg.WebhookWorkers
	if workers == 0 {
		workers = 10
	}
	pool := newWorkerPool(a.cfg.DB, store, realClock{}, workers)
	a.webhookPool = pool

	// Register webhook delivery as signal bus subscribers so that every
	// content lifecycle event enqueues delivery jobs.
	for _, sig := range []Signal{
		AfterCreate, AfterUpdate, AfterPublish, AfterUnpublish,
		AfterSchedule, AfterArchive, AfterDelete,
	} {
		s := sig
		a.OnSignal(s, func(ctx context.Context, ev SignalEvent) error {
			return webhookDispatch(ctx, ev, s, store, pool)
		})
	}
	return a
}

// Audit wires store as the audit trail for this application. It subscribes to
// [AfterPublish], [AfterSchedule], [AfterArchive], and [AfterDelete] on the
// signal bus and persists an [AuditRecord] for each event. Errors from
// [AuditStore.Append] are logged at Warn level and never propagated to the caller.
//
// Audit also mounts GET /_audit — an Editor-or-higher HTTP endpoint that
// returns a JSON array of [AuditRecord] values. Optional query parameters:
// from, to (RFC3339), type (content type name), actor (actor ID).
//
// The smeldr_audit_log table must exist before Audit is called.
// See [NewAuditStore] for the required DDL.
func (a *App) Audit(store AuditStore) *App {
	a.auditStore = store
	for _, sig := range []Signal{AfterPublish, AfterSchedule, AfterArchive, AfterDelete} {
		s := sig
		a.OnSignal(s, func(ctx context.Context, ev SignalEvent) error {
			r := AuditRecord{
				ID:            NewID(),
				Timestamp:     ev.Timestamp,
				Signal:        s,
				ContentType:   ev.Type,
				Slug:          ev.Slug,
				ActorID:       ev.ActorID,
				ActorRole:     ev.ActorRole,
				PreviousState: ev.PreviousState,
			}
			if err := store.Append(ctx, r); err != nil {
				slog.WarnContext(ctx, "smeldr: audit append failed",
					"error", err, "signal", s, "type", ev.Type, "slug", ev.Slug)
			}
			return nil
		})
	}
	return a
}

// WebhookStore returns the configured [WebhookStore], or nil when outbound
// webhooks have not been configured via [App.Webhooks].
// forge-mcp calls this in its New constructor to wire webhook admin tools.
func (a *App) WebhookStore() *WebhookStore { return a.webhookStore }

// WebhookJobQueue is the interface through which forge-mcp accesses the
// outbound webhook worker pool. It is satisfied by the unexported workerPool
// type returned by [App.WebhookPool].
type WebhookJobQueue interface {
	Enqueue(ctx context.Context, job OutboundJob) error
	RetryDead(ctx context.Context, jobID string) error
	ListDeliveryLogs(ctx context.Context, jobID string) ([]DeliveryLog, error)
	ListJobsForEndpoint(ctx context.Context, endpointID string) ([]OutboundJob, error)
	DeliveryStats(ctx context.Context, endpointID string) (total, success, failed int, lastAttempt *time.Time, err error)
}

// WebhookPool returns the outbound webhook worker pool as a [WebhookJobQueue],
// or nil when webhooks have not been configured via [App.Webhooks].
// forge-mcp calls this in its New constructor to wire delivery log tools.
func (a *App) WebhookPool() WebhookJobQueue {
	if a.webhookPool == nil {
		return nil
	}
	return a.webhookPool
}

// AddSignalListener registers a function that is called after every lifecycle
// signal fired by any registered content module. fn receives the signal, the
// unqualified content type name (e.g. "Post"), and the content item.
//
// Listeners are invoked synchronously inside the afterHook goroutine — keep
// them non-blocking or spawn their own goroutines for heavy work.
//
// AddSignalListener is the low-level hook used by forge-mcp to implement
// resource subscription notifications. Application code can also use it to
// build custom event pipelines.
func (a *App) AddSignalListener(fn func(Signal, string, any)) {
	a.signalListeners = append(a.signalListeners, fn)
}

// OnSignal registers a handler that is called after every lifecycle signal
// matching sig. Handlers are called sequentially in registration order within
// the signal bus goroutine (see [App.wireSignalBus]).
//
// The bus wraps the context with [context.WithoutCancel] and enforces a 100 ms
// per-handler deadline. Handler errors and deadline exceeded are logged with
// [slog.Warn] and never propagated to the caller that triggered the signal.
//
// Use OnSignal to build custom delivery pipelines that react to content
// lifecycle events:
//
//	app.OnSignal(smeldr.AfterPublish, func(ctx context.Context, ev smeldr.SignalEvent) error {
//	    return myQueue.Enqueue(ctx, ev)
//	})
func (a *App) OnSignal(sig Signal, h func(context.Context, SignalEvent) error) *App {
	a.busMu.Lock()
	defer a.busMu.Unlock()
	if a.busHandlers == nil {
		a.busHandlers = make(map[Signal][]func(context.Context, SignalEvent) error)
	}
	a.busHandlers[sig] = append(a.busHandlers[sig], h)
	return a
}

// dispatchBus dispatches ev to all handlers registered for sig via [App.OnSignal].
// Called from the wireSignalBus closure inside the afterHook goroutine.
// Each handler runs with a fresh context derived from context.WithoutCancel(ctx)
// and a 100 ms timeout so that client disconnects do not abort delivery.
// Handler errors are logged; nothing is returned or propagated.
func (a *App) dispatchBus(ctx context.Context, ev SignalEvent, sig Signal) {
	a.busMu.RLock()
	handlers := a.busHandlers[sig]
	a.busMu.RUnlock()
	if len(handlers) == 0 {
		return
	}
	base := context.WithoutCancel(ctx)
	for _, h := range handlers {
		hCtx, cancel := context.WithTimeout(base, 100*time.Millisecond)
		err := h(hCtx, ev)
		cancel()
		if err != nil {
			slog.WarnContext(ctx, "signal bus handler error",
				"signal", sig, "type", ev.Type, "slug", ev.Slug, "error", err)
		}
	}
}

// wireSignalBus constructs the afterHook closure and injects it into every
// hookable module collected by Content(). Called once by Run() before
// starting the HTTP server. The closure builds a [SignalEvent], dispatches
// it to all registered [App.OnSignal] handlers, then calls any legacy
// [App.AddSignalListener] callbacks.
func (a *App) wireSignalBus() {
	a.busMu.RLock()
	hasBus := len(a.busHandlers) > 0
	a.busMu.RUnlock()
	if !hasBus && len(a.signalListeners) == 0 {
		return
	}
	app := a
	listeners := a.signalListeners

	fn := func(ctx Context, sig Signal, meta afterHookMeta, item any) {
		ev := buildSignalEvent(ctx, sig, meta, item, app.cfg.BaseURL)
		app.dispatchBus(ctx, ev, sig)
		for _, l := range listeners {
			l(sig, meta.TypeName, item)
		}
	}

	for _, m := range a.hookableModules {
		m.setAfterHook(fn)
	}
}

// Nav registers navigation items for [NavModeCode]. Calling Nav implicitly
// activates code-mode navigation — no database table is created or read.
// Items are deep-copied at [App.Handler] time; the caller's slice is not
// retained after that point.
//
// Nav must be called before [App.Handler] or [App.Run].
func (a *App) Nav(items ...NavItem) {
	a.navCodeItems = append(a.navCodeItems, items...)
}

// NavTree returns the application's [NavTree], or nil when navigation has not
// been configured. NavTree is non-nil only after [App.Handler] or [App.Run]
// has been called.
//
// forge-mcp calls this in its New constructor to wire nav tools.
func (a *App) NavTree() *NavTree { return a.navTree }

// httpsRedirect returns a middleware that redirects plain-HTTP requests to
// their HTTPS equivalents with a 301 Moved Permanently response.
//
// The redirect is skipped when the request is already over TLS (r.TLS != nil)
// or when the X-Forwarded-Proto header equals "https" (reverse-proxy scenario).
//
// GET /_health is always exempt so that reverse-proxy health checks (e.g.
// Caddy health_uri) receive a 200 response without being redirected
// (Amendment A59).
func httpsRedirect() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/_health" {
				next.ServeHTTP(w, r)
				return
			}
			if r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https" {
				next.ServeHTTP(w, r)
				return
			}
			target := "https://" + r.Host + r.RequestURI
			http.Redirect(w, r, target, http.StatusMovedPermanently)
		})
	}
}

// Handler returns the composed http.Handler that serves all registered routes
// behind the global middleware stack.
//
// When Config.HTTPS is true, an HTTP→HTTPS redirect middleware is prepended
// before all user-supplied middleware.
//
// Handler is called automatically by [App.Run]. Call it directly when you need
// to hand the handler to your own server (e.g. for testing or embedding):
//
//	srv := &http.Server{Handler: app.Handler()}
func (a *App) Handler() http.Handler {
	if a.sitemapStore != nil && !a.sitemapIndexRegistered {
		a.sitemapIndexRegistered = true
		a.mux.Handle("GET /sitemap.xml", a.sitemapStore.IndexHandler(a.cfg.BaseURL))
	}
	if a.seo.robots != nil && !a.robotsTxtRegistered {
		a.robotsTxtRegistered = true
		a.mux.Handle("GET /robots.txt", RobotsTxtHandler(*a.seo.robots, a.cfg.BaseURL))
	}
	if a.llmsStore != nil && a.llmsStore.HasCompact() && !a.llmsTxtRegistered {
		a.llmsTxtRegistered = true
		a.mux.Handle("GET /llms.txt", a.llmsStore.CompactHandler())
	}
	if a.llmsStore != nil && a.llmsStore.HasFull() && !a.llmsFullTxtRegistered {
		a.llmsFullTxtRegistered = true
		a.mux.Handle("GET /llms-full.txt", a.llmsStore.FullHandler())
	}
	if a.feedStore != nil && a.feedStore.HasFeeds() && !a.feedIndexRegistered {
		a.feedIndexRegistered = true
		a.mux.Handle("GET /feed.xml", a.feedStore.IndexHandler())
	}
	if len(a.cookieDecls) > 0 && !a.cookieManifestReg {
		a.cookieManifestReg = true
		u, _ := url.Parse(a.cfg.BaseURL)
		a.mux.Handle("GET /.well-known/cookies.json",
			newCookieManifestHandler(u.Hostname(), a.cookieDecls, a.cookieManifestOpts...),
		)
	}
	if !a.redirectManifestReg {
		a.redirectManifestReg = true
		u2, _ := url.Parse(a.cfg.BaseURL)
		a.mux.Handle("GET /.well-known/redirects.json",
			newRedirectManifestHandler(u2.Hostname(), a.redirectStore, a.redirectManifestOpts...),
		)
	}
	// Dynamic content: load runtime-defined types from DB and register routes.
	// Must be done before the standalone dispatch block so the 2-segment
	// wildcard and /_content/ routes are registered first.
	if a.dynamicContentEnabled {
		a.loadDynamicTypes(context.Background())
	}
	if a.dynamicContentEnabled && !a.dynamicContentReg {
		a.dynamicContentReg = true
		dynAuth := a.cfg.Auth
		if dynAuth == nil {
			dynAuth = BearerHMAC(string(a.cfg.Secret))
		}
		a.mux.Handle("POST /_content/types", newDefineTypeHandler(a, dynAuth))
		a.mux.Handle("GET /_content/{type}", newAdminListHandler(a, dynAuth))
		a.mux.Handle("GET /_content/{type}/{id}", newAdminGetHandler(a, dynAuth))
		a.mux.Handle("POST /_content/{type}", newCreateContentHandler(a, dynAuth))
		a.mux.Handle("PATCH /_content/{type}/{id}", newUpdateContentHandler(a, dynAuth))
		a.mux.Handle("POST /_content/{type}/{id}/status", newSetStatusHandler(a, dynAuth))
	}
	// Single-segment dispatch: GET /{slug} routes to dynamic list, standalone
	// modules, or the redirect store (404 fallback). Always registered so that
	// the redirect store is reached via a consistent path regardless of whether
	// standalone modules are present.
	//
	// GET /{slug}/aidoc is only registered when standalone modules exist; the
	// 2-segment literal-wildcard pattern conflicts with per-module patterns
	// like GET /posts/{slug} registered by non-standalone modules.
	if !a.standaloneReg {
		a.standaloneReg = true
		sds := a.standaloneModules
		rs := a.redirectStore
		a.mux.Handle("GET /{slug}", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			slug := r.PathValue("slug")
			for _, sd := range sds {
				if sd.findAndServe(w, r, slug) {
					return
				}
			}
			rs.handler().ServeHTTP(w, r)
		}))
		if len(sds) > 0 {
			a.mux.Handle("GET /{slug}/aidoc", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				slug := r.PathValue("slug")
				for _, sd := range sds {
					if sd.findAndServeAIDoc(w, r, slug) {
						return
					}
				}
				WriteError(w, r, ErrNotFound)
			}))
		}
	}
	if !a.redirectFallbackReg {
		a.redirectFallbackReg = true
		a.mux.Handle("/", a.redirectStore.handler())
	}
	// D30: auto-apply Config.AppSchema and Config.OGDefaults loaded from
	// smeldr.config. App.SEO() calls take precedence (applied only when nil).
	if a.cfg.AppSchema != nil && a.seo.appSchema == nil {
		a.seo.appSchema = a.cfg.AppSchema
	}
	if a.cfg.OGDefaults != nil && a.seo.ogDefaults == nil {
		og := a.cfg.OGDefaults
		// Resolve root-relative og_image path against BaseURL so scrapers
		// receive an absolute URL (e.g. "/static/og.png" → "https://example.com/static/og.png").
		if strings.HasPrefix(og.Image.URL, "/") && a.cfg.BaseURL != "" {
			resolved := &OGDefaults{
				TwitterSite:    og.TwitterSite,
				TwitterCreator: og.TwitterCreator,
				Image: Image{
					URL:    strings.TrimRight(a.cfg.BaseURL, "/") + og.Image.URL,
					Width:  og.Image.Width,
					Height: og.Image.Height,
				},
			}
			a.seo.ogDefaults = resolved
		} else {
			a.seo.ogDefaults = og
		}
	}
	if len(a.templateModules) > 0 {
		bindErrorTemplates(a.templateModules)
		for _, tp := range a.templateModules {
			if s, ok := tp.(interface {
				setSEODefaults(*OGDefaults, *AppSchema, *HeadAssets)
			}); ok {
				s.setSEODefaults(a.seo.ogDefaults, a.seo.appSchema, a.seo.headAssets)
			}
		}
	}
	if a.auditStore != nil && !a.auditHandlerReg {
		a.auditHandlerReg = true
		auditAuth := a.cfg.Auth
		if auditAuth == nil {
			auditAuth = BearerHMAC(string(a.cfg.Secret))
		}
		a.mux.Handle("GET /_audit", newAuditHandler(auditAuth, a.auditStore))
	}
	if a.logRing != nil && !a.logsHandlerReg {
		a.logsHandlerReg = true
		logsAuth := a.cfg.Auth
		if logsAuth == nil {
			logsAuth = BearerHMAC(string(a.cfg.Secret))
		}
		a.mux.Handle("GET /_logs", newLogsHandler(logsAuth, a.logRing))
	}
	// A66: probe smeldr_tokens table at startup when a TokenStore is configured.
	// A83: auto-create a bootstrap admin token when smeldr_tokens is empty.
	if a.tokenStore != nil {
		if err := a.tokenStore.probeTable(context.Background()); err != nil {
			fmt.Fprintf(os.Stderr, "WARN  forge: TokenStore is configured but the smeldr_tokens table is missing or inaccessible — create it using the DDL in the TokenStore documentation\n")
		} else {
			a.tokenStore.ensureBootstrap(context.Background())
		}
	}
	// D29: initialise the navigation tree when NavMode is set or App.Nav() items
	// were supplied. NavModeDB migrates and loads from smeldr_nav; NavModeCode
	// builds the tree from the items supplied via App.Nav().
	if a.cfg.NavMode == NavModeDB {
		if a.cfg.DB == nil {
			panic("smeldr: Config.NavMode is NavModeDB but Config.DB is nil — set Config.DB or use NavModeCode")
		}
		u, _ := url.Parse(a.cfg.BaseURL)
		navCtx := NewBackgroundContext(u.Hostname())
		a.navTree = &NavTree{}
		if err := a.navTree.migrate(navCtx, a.cfg.DB); err != nil {
			fmt.Fprintf(os.Stderr, "WARN  forge: NavTree migration failed: %v\n", err)
			a.navTree = nil
		} else if err := a.navTree.load(navCtx, a.cfg.DB); err != nil {
			fmt.Fprintf(os.Stderr, "WARN  forge: NavTree load failed: %v\n", err)
			a.navTree = nil
		}
	} else if len(a.navCodeItems) > 0 {
		a.navTree = &NavTree{}
		a.navTree.setCode(a.navCodeItems)
	}
	if a.navTree != nil {
		for _, m := range a.navTreeModules {
			m.setNavTree(a.navTree)
		}
	}
	// A34: trigger a one-shot startup rebuild of all derived content (sitemap,
	// feed, AI index) so that items already in the repository at server start
	// (seed data, pre-loaded fixtures) are reflected before the first request.
	if !a.rebuildDone && len(a.rebuilderModules) > 0 {
		a.rebuildDone = true
		u, _ := url.Parse(a.cfg.BaseURL)
		ctx := NewBackgroundContext(u.Hostname())
		modules := a.rebuilderModules
		go func() {
			for _, rb := range modules {
				rb.rebuildAll(ctx)
			}
		}()
	}
	mws := a.middleware
	if a.cfg.HTTPS {
		mws = append([]func(http.Handler) http.Handler{httpsRedirect()}, mws...)
	}
	return Chain(a.mux, mws...)
}

// SEO applies one or more app-level SEO options. Valid SEOOption types are:
//
//   - [*RobotsConfig] — robots.txt policy and AI-crawler directives
//   - [*OGDefaults] — fallback Open Graph image and Twitter site handle
//   - [*AppSchema] — JSON-LD Organization/Person schema emitted on every page
//   - [*HeadAssets] — canonical CSS/JS asset paths included in every page <head>
//
// Call SEO before [App.Handler] or [App.Run] so the configuration is applied
// before routes are registered. SEO may be called multiple times; later calls
// override earlier values for the same option type.
//
//	app.SEO(
//		&smeldr.RobotsConfig{AIScraper: smeldr.AskFirst, Sitemaps: true},
//		&smeldr.OGDefaults{Image: "https://example.com/og.png", TwitterSite: "@example"},
//		&smeldr.AppSchema{OrgName: "Example Inc", OrgType: "Organization"},
//	)
func (a *App) SEO(opts ...SEOOption) {
	for _, opt := range opts {
		opt.applySEO(&a.seo)
	}
}

// Cookies registers cookie declarations for the compliance manifest at
// /.well-known/cookies.json. Call once at startup with all cookies the
// application may set.
//
// Duplicate declarations (same Name) are silently deduplicated; the first
// declaration with a given name wins.
//
// Optionally pass [ManifestAuth] to restrict the manifest endpoint to
// authenticated requests:
//
//	app.Cookies(
//	    smeldr.Cookie{Name: "session", Category: smeldr.Necessary, ...},
//	    smeldr.Cookie{Name: "prefs",   Category: smeldr.Preferences, ...},
//	)
func (a *App) Cookies(decls ...Cookie) {
	seen := make(map[string]struct{}, len(a.cookieDecls))
	for _, d := range a.cookieDecls {
		seen[d.Name] = struct{}{}
	}
	for _, d := range decls {
		if _, ok := seen[d.Name]; !ok {
			a.cookieDecls = append(a.cookieDecls, d)
			seen[d.Name] = struct{}{}
		}
	}
}

// CookiesManifestAuth sets the [AuthFunc] that guards /.well-known/cookies.json.
// Call before [App.Handler] or [App.Run].
//
//	app.CookiesManifestAuth(smeldr.BearerHMAC(secret, smeldr.Editor))
func (a *App) CookiesManifestAuth(auth AuthFunc) {
	a.cookieManifestOpts = append(a.cookieManifestOpts, ManifestAuth(auth))
}

// Redirect registers a manual redirect rule. Chain collapse is applied
// automatically: if from already redirects to an intermediate path and this
// call adds a rule for that intermediate path, the chain is collapsed (A→B
// + B→C = A→C). Maximum collapse depth is 10 (Decision 24).
//
// To issue a 301 Moved Permanently:
//
//	app.Redirect("/old-path", "/new-path", smeldr.Permanent)
//
// To issue a 410 Gone (pass an empty destination):
//
//	app.Redirect("/removed", "", smeldr.Gone)
func (a *App) Redirect(from, to string, code RedirectCode) {
	a.redirectStore.Add(RedirectEntry{From: from, To: to, Code: code})
}

// RedirectStore returns the App's [RedirectStore], which can be used to load
// persisted redirects from a database at startup, or to save/remove entries
// at runtime:
//
//	if err := app.RedirectStore().Load(ctx, db); err != nil {
//	    log.Fatal(err)
//	}
func (a *App) RedirectStore() *RedirectStore {
	return a.redirectStore
}

// Redirects activates database-backed redirect management. It creates the
// smeldr_redirects table if it does not exist, loads any saved entries into
// the in-memory store so they are immediately active, and stores db so that
// runtime MCP and CLI operations can persist changes without a restart.
//
// Call once at application startup before [App.Handler] or [App.Run]:
//
//	if err := app.Redirects(db); err != nil {
//	    log.Fatal(err)
//	}
//
// MCP redirect tools (create_redirect, list_redirects, delete_redirect) are
// only registered when Redirects has been called.
func (a *App) Redirects(db DB) error {
	if err := CreateRedirectsTable(db); err != nil {
		return err
	}
	a.redirectDB = db
	return a.redirectStore.Load(context.Background(), db)
}

// RedirectDB returns the DB passed to [App.Redirects], or nil if
// database-backed redirect management has not been activated. Used by
// smeldr.dev/mcp to gate and service the redirect management tools.
func (a *App) RedirectDB() DB { return a.redirectDB }

// RedirectManifestAuth sets the [AuthFunc] that guards /.well-known/redirects.json.
// Call before [App.Handler] or [App.Run].
//
//	app.RedirectManifestAuth(smeldr.BearerHMAC(secret, smeldr.Editor))
func (a *App) RedirectManifestAuth(auth AuthFunc) {
	a.redirectManifestOpts = append(a.redirectManifestOpts, ManifestAuth(auth))
}

// ServeDynamicContent activates the dynamic content substrate. It creates the
// necessary database tables (smeldr_content_type_schemas, smeldr_dynamic_content)
// and migrates existing tables. Handler() will then register the /_content/ admin
// namespace and, for each content type with a URLPrefix, specific public routes.
// Panics when Config.DB is nil.
//
//	smeldr.CreateSchemaTable(db)   // optional: ServeDynamicContent calls this
//	app.ServeDynamicContent()
func (a *App) ServeDynamicContent() *App {
	if a.cfg.DB == nil {
		panic("smeldr: ServeDynamicContent requires Config.DB")
	}
	if err := CreateSchemaTable(a.cfg.DB); err != nil {
		panic("smeldr: ServeDynamicContent CreateSchemaTable: " + err.Error())
	}
	if err := MigrateSchemaKindColumn(a.cfg.DB); err != nil {
		slog.Warn("smeldr: ServeDynamicContent MigrateSchemaKindColumn", "err", err)
	}
	if err := MigrateURLPrefixColumn(a.cfg.DB); err != nil {
		slog.Warn("smeldr: ServeDynamicContent MigrateURLPrefixColumn", "err", err)
	}
	if err := CreateBlockTables(a.cfg.DB); err != nil {
		panic("smeldr: ServeDynamicContent CreateBlockTables: " + err.Error())
	}
	if a.sitemapStore == nil {
		a.sitemapStore = NewSitemapStore()
	}
	a.dynamicContentEnabled = true
	return a
}

// forgeVersions reads the binary's embedded build info and returns a map of
// short module name → version for all Smeldr core and companion modules
// (smeldr.dev/core and related modules). Each module path under
// smeldr.dev/ maps to a key equal to the sub-path
// (e.g. smeldr.dev/mcp → "mcp", smeldr.dev/core → "core").
// The leading "v" is stripped from version strings ("v1.1.5" → "1.1.5").
// Returns nil when build info is unavailable or no smeldr modules are found.
func forgeVersions() map[string]string {
	const base = "smeldr.dev/"
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return nil
	}
	result := make(map[string]string)
	add := func(path, version string) {
		if !strings.HasPrefix(path, base) || version == "" {
			return
		}
		v := strings.TrimPrefix(version, "v")
		key := strings.ReplaceAll(strings.TrimPrefix(path, base), "-", "_")
		result[key] = v
	}
	add(info.Main.Path, info.Main.Version)
	for _, dep := range info.Deps {
		add(dep.Path, dep.Version)
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

// Health mounts GET /_health on the App's mux.
//
// The endpoint always returns HTTP 200 with Content-Type application/json.
// Framework versions are read from the binary's embedded build info and
// included in the response. The core module uses the key "core";
// companion modules use a key derived from their sub-path (e.g. "mcp").
// When build info is unavailable, only {"status":"ok"} is returned.
//
// Call Health before [App.Handler] or [App.Run]:
//
//	app.Health()
//	// GET /_health → {"status":"ok","core":"1.25.0","mcp":"1.11.2"}
func (a *App) Health() {
	versions := forgeVersions()
	// Pre-sort companion module keys for deterministic JSON output.
	var companions []string
	for k := range versions {
		if k != "core" {
			companions = append(companions, k)
		}
	}
	slices.Sort(companions)

	a.mux.Handle("GET /_health", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		var b strings.Builder
		b.WriteString(`{"status":"ok"`)
		if v, ok := versions["core"]; ok {
			fmt.Fprintf(&b, `,"core":%q`, v)
		}
		for _, k := range companions {
			fmt.Fprintf(&b, `,%q:%q`, k, versions[k])
		}
		b.WriteByte('}')
		fmt.Fprint(w, b.String())
	}))
}

// Run starts the HTTP server on addr (e.g. ":8080") and blocks until
// SIGINT or SIGTERM is received.
//
// On receiving a signal, Run initiates a graceful shutdown with a 5-second
// deadline, waits for active connections to drain, and returns nil.
// Non-shutdown errors from ListenAndServe are returned directly.
//
//	if err := app.Run(":8080"); err != nil {
//	    log.Fatal(err)
//	}
func (a *App) Run(addr string) error {
	// Load shared partials once, then push to each module before parsing.
	partials, err := loadPartials(a.partialsDir)
	if err != nil {
		return err
	}
	if len(partials) > 0 {
		for _, tp := range a.templateModules {
			if sp, ok := tp.(interface{ setPartials([]string) }); ok {
				sp.setPartials(partials)
			}
		}
	}

	// Parse HTML templates before starting the server. Fail fast so startup
	// errors are obvious rather than surfacing as 406 responses at request time.
	for _, tp := range a.templateModules {
		if err := tp.parseTemplates(); err != nil {
			return err
		}
	}

	// Log framework versions at startup.
	if versions := forgeVersions(); len(versions) > 0 {
		var parts []string
		if v, ok := versions["core"]; ok {
			parts = append(parts, "core "+v)
		}
		companions := make([]string, 0, len(versions))
		for k := range versions {
			if k != "core" {
				companions = append(companions, k)
			}
		}
		slices.Sort(companions)
		for _, k := range companions {
			parts = append(parts, k+" "+versions[k])
		}
		fmt.Fprintf(os.Stderr, "smeldr: %s\n", strings.Join(parts, ", "))
	}

	srv := &http.Server{
		Addr:         addr,
		Handler:      a.Handler(),
		ReadTimeout:  a.cfg.ReadTimeout,
		WriteTimeout: a.cfg.WriteTimeout,
		IdleTimeout:  a.cfg.IdleTimeout,
	}

	// serveErr receives the result of ListenAndServe.
	serveErr := make(chan error, 1)

	// Inject webhook delivery hooks and signal listeners into all modules.
	a.wireSignalBus()

	// Start the webhook worker pool if configured.
	poolCtx, poolCancel := context.WithCancel(context.Background())
	defer poolCancel()
	if a.webhookPool != nil {
		a.webhookPool.Start(poolCtx)
		defer a.webhookPool.Stop()
	}

	// Start the scheduled-publishing ticker if any modules were registered.
	if len(a.schedulerModules) > 0 {
		u, _ := url.Parse(a.cfg.BaseURL)
		bgCtx := NewBackgroundContext(u.Hostname())
		sched := newScheduler(a.schedulerModules, bgCtx)
		schedCtx, schedCancel := context.WithCancel(context.Background())
		sched.Start(schedCtx)
		defer func() {
			schedCancel()
			sched.Wait()
		}()
	}

	go func() {
		serveErr <- srv.ListenAndServe()
	}()

	// Block until an OS signal or a fatal server error.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	select {
	case err := <-serveErr:
		// Server failed before any signal — return the error directly.
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	case <-ctx.Done():
		// Signal received — begin graceful shutdown.
		stop()
	}

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		return err
	}
	for _, sp := range a.stoppableModules {
		sp.Stop()
	}
	return nil
}
